### ISSUE TITLE
Add the new 3pool & gusd vaults please

### ISSUE THREAD

**Issue by DarkGhost7** [brschkv/yearn-roi-webapp#1]
https://etherscan.io/address/0x9ca85572e6a3ebf24dedd195623f188735a5179f 
you can also find the new vaults at y.finance

**Comment by brschkv** [comment]
fixed with https://github.com/brschkv/yearn-roi-model/commit/5a7d78656b304af2500f57aa58dfa160b5aa6ac0

**Comment by brschkv** [comment]
@DarkGhost7 thanks for the heads up. New vaults can now be selected at https://yearn-roi.xyz

**Comment by DarkGhost7** [comment]
Awesome!
